# Generated by Django 5.2.8 on 2025-11-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], help_text='Select province/territory', max_length=2)),
                ('zipcode', models.CharField(max_length=20)),
                ('country', models.CharField(default='Canada', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('monday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('tuesday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('wednesday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('thursday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('friday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('saturday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('sunday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('accepts_dropoff', models.BooleanField(default=True)),
                ('offers_pickup', models.BooleanField(default=False)),
                ('accepts_donations', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city'], name='centers_rec_city_22ab3e_idx'), models.Index(fields=['state'], name='centers_rec_state_36d98b_idx'), models.Index(fields=['zipcode'], name='centers_rec_zipcode_4d5b7e_idx')],
            },
        ),
    ]
