# Generated by Django 5.2.8 on 2025-11-23 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('country', models.CharField(default='Canada', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('monday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('tuesday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('wednesday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('thursday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('friday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('saturday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('sunday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('accepts_dropoff', models.BooleanField(default=True)),
                ('offers_pickup', models.BooleanField(default=False)),
                ('accepts_donations', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city'], name='centers_rec_city_22ab3e_idx'), models.Index(fields=['state'], name='centers_rec_state_36d98b_idx'), models.Index(fields=['zipcode'], name='centers_rec_zipcode_4d5b7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcceptedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('paper', 'Paper'), ('plastic', 'Plastic'), ('glass', 'Glass'), ('metal', 'Metal'), ('electronics', 'Electronics'), ('batteries', 'Batteries'), ('textiles', 'Textiles'), ('organic', 'Organic Waste'), ('hazardous', 'Hazardous Materials')], max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Special requirements or notes')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='centers.recyclingcenter')),
            ],
            options={
                'unique_together': {('center', 'material_type')},
            },
        ),
    ]
